sonar.projectKey=albaestherespejo1234_app-vulnerable-sesion4
sonar.organization=albaestherespejo1234
sonar.projectName=app-vulnerable-sesion4
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=py
